### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by bnainar** [SamHSmith/rivos#1]
We need a code of conduct. Without one people with whose politics we don't agree might contribute.
This is dangerous as it would hurt the minorities which elected us as their representatives.

If we fail to do this, collaborative work will decline. We seek in this project to create an inclusive community where coders from a variety of backgrounds are able to work together. Several of us are uncomfortable collaborating and/or interacting on a platform without a code of conduct, both because it is antithetical towards our core
identities and we are uneasy to potentially link our reputations with potential non-inclusive bigots through co-authorship.

Therefore we need to make sure we can exclude such people from this inclusive space.

Failure to do say may result in Sam being cancelled and removed from this rivos project

**Comment by SamHSmith** [comment]
Humanity has managed to exist and thrive on this planet without a CoC for 200 000 years. Rivos is sooooo inclusive that we do not have a CoC in case we offend those who don't like them.
